name: Deploy to Netlify

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t project1 ./apps/project1
          docker build -t project2 ./apps/project2

      # Step 4: Deploy to Netlify
      - name: Deploy to Netlify
        uses: netlify/actions/deploy@v2.0.0
        with:
          publish-dir: ./apps/project1/out  # Path to the built project output
          production: true                 # Deploy to the production site
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.PROJECT1_SITE_ID }}
